### ISSUE TITLE
Question about your remark on mongo-testing.

### ISSUE THREAD

**Issue by warreee** [jmcdo29/testing-nestjs#978]
Hi Jay
In your comments above [this](https://github.com/jmcdo29/testing-nestjs/blob/master/apps/mongo-sample/src/cat/cat.service.ts#L48) line you argue not using `save` method because it is hard to mock.
I came across this because I was indeed trying to mock it and I don't get it to work.
Can you elaborate on why you can't just do:
jest.spyOn(model, 'save').mockResolvedValueOnce({...}); 
But the following is no problem?
jest.spyOn(model, 'create').mockResolvedValueOnce({...});

**Comment by jmcdo29** [comment]
@warreee I never said anything about `save` as a method. I suggested not using `new this.model()` because _that's_ what becomes difficult to mock. When you create a new instance of the thing you're mocking, it gets messy. It's the difference of using an [Active Record](https://en.wikipedia.org/wiki/Active_record_pattern) approach (where each instance of a model or entity has its own Data Manipulation Methods) vs a [Data Mapper](https://en.wikipedia.org/wiki/Data_mapper_pattern) approach (where you use a central service and pass entities and models to it so it can talk with the database).

**Comment by warreee** [comment]
Alright, thanks for the clarification.
However, do you have an idea of why I can't do:
`jest.spyOn(model, 'save').mockResolvedValueOnce({...});`
But I can do:
`jest.spyOn(model, 'create').mockResolvedValueOnce({...});`

The `save` method seems not to be able to be spied on, however as in your example tests for `create`, `update`, `findOne` ... this works perfectly fine?
I tried this also in your mongo example so that I was sure it was not my project setup messing with this...

**Comment by jmcdo29** [comment]
Yes, because when you do `new this.model()` (which creates the `Document` instance that has the `save` method), you no longer are working with `this.model`, but the returned object of that. If you look at the types, `Model` has no method called `save`.

**Comment by warreee** [comment]
I see thanks!
